create table order_items (
    quantidade integer not null,
    id bigint generated by default as identity,
    order_id bigint not null,
    preco_unitario_centavos bigint not null,
    product_id bigint not null,
    primary key (id)
);

create table orders (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    total_centavos bigint not null,
    user_id bigint not null,
    status varchar(255) not null check ((status in ('PENDENTE','PAGO','CANCELADO'))),
    primary key (id)
);

create table payments (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    order_id bigint not null,
    gateway varchar(255) not null check ((gateway in ('STRIPE','MERCADOPAGO'))),
    gateway_payment_id varchar(255),
    status varchar(255) not null check ((status in ('PENDENTE','APROVADO','RECUSADO'))),
    primary key (id)
);

create table products (
    ativo boolean not null,
    stock integer not null,
    cents_price bigint not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    image_url varchar(512),
    description TEXT,
    name varchar(255) not null,
    primary key (id)
);

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    email varchar(255) not null unique,
    name varchar(255) not null,
    role varchar(255) not null check ((role in ('ADMIN','CLIENTE'))),
    senha_hash varchar(255) not null,
    primary key (id)
);
